### ISSUE TITLE
[Crash] End Remastered preventing startup

### ISSUE THREAD

**Issue by Eatham532** [Team-Remastered/End-Remastered-Fabric#2]
```shell
main/ERROR17:47:42
Failed to start the minecraft server
Console17:47:42
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'endrem'!
at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.8.jar:?]
at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric.jar:0.11.0]
Caused by: java.lang.NullPointerException: Cannot read field "common" because "data" is null
at com.teamremastered.endrem.config.ERConfigHandler.load(ERConfigHandler.java:31) ~[fabric-end-remastered-5.1.0-1.19.jar:?]
at com.teamremastered.endrem.registry.RegisterHandler.init(RegisterHandler.java:11) ~[fabric-end-remastered-5.1.0-1.19.jar:?]
at com.teamremastered.endrem.EndRemastered.onInitialize(EndRemastered.java:29) ~[fabric-end-remastered-5.1.0-1.19.jar:?]
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
... 8 more
```

Edit: Deleting the End Remastered config fixes this bug.

**Comment by Jack-Bagel** [comment]
Did you edit the config file before the crash or did you have an older version of the config?

**Comment by Eatham532** [comment]
Ah I think your right. Whenever i would update my mods that would happen it would crash. Maybe you could add a protection so tha tg it does not crash. Like create a new config and change the old one to a backup version. The new config could also be changed to have the configurations that the old config had.

**Comment by Jack-Bagel** [comment]
I'll try to implement a default config and a warning message in the case that the config file can't be read.

**Comment by Eatham532** [comment]
Thanks
